export type AllResults = {
  data: Race[];
}

export type Race = {
  race_id: number;
  race_name: string;
  venue_name: string;
  match_date: string;
  start_date: string;
  end_date: string;
  country: string;
  country_code: string;
  sessions: string[];
  results: Result[];
};

export type Result = {
  gap: string;
  pos: string;
  laps: string;
  name: string;
  pits: string;
  team: string;
  time: string;
  point: number;
  country: string;
  team_slug: string;
  driver_slug: string;
};

export type FormattedRaceResult = {
  round: string;
  raceName: string;
  results: FormattedDriverResult[]
  circuit: {
    country: string;
    locality: string
  }
};
  
export type FormattedDriverResult = {
  position: string;
  driver: {
    id: string;
    name: string;
  };
  team: string;
}

const allResults: AllResults = {
  "data": [
    {
      "race_id": 1132,
      "race_name": "Miami Grand Prix",
      "venue_name": "Miami International Autodrome",
      "match_date": "2025-05-05",
      "start_date": "2025-05-02T16:30:00Z",
      "end_date": "2025-05-04T22:00:00Z",
      "country": "USA",
      "country_code": "USA",
      "sessions": [
        "Practice 1",
        "Sprint Shootout 1",
        "Sprint Shootout 2",
        "Sprint Shootout 3",
        "Sprint Grid",
        "Sprint",
        "Qualifying 1",
        "Qualifying 2",
        "Qualifying 3",
        "Grid",
        "Race",
        "FastestLap"
      ],
      "results": [
        {
          "gap": "1:28:51.587",
          "pos": "1",
          "laps": "57",
          "name": "Oscar Piastri",
          "pits": "1",
          "team": "McLaren",
          "time": "1:28:51.587",
          "point": 25,
          "country": "Australia",
          "team_slug": "mclaren",
          "driver_slug": "oscar-piastri"
        },
        {
          "gap": "4.630",
          "pos": "2",
          "laps": "57",
          "name": "Lando Norris",
          "pits": "1",
          "team": "McLaren",
          "time": "+4.630s",
          "point": 18,
          "country": "Great Britain",
          "team_slug": "mclaren",
          "driver_slug": "lando-norris"
        },
        {
          "gap": "37.644",
          "pos": "3",
          "laps": "57",
          "name": "George Russell",
          "pits": "1",
          "team": "Mercedes",
          "time": "+37.644s",
          "point": 15,
          "country": "Great Britain",
          "team_slug": "mercedes",
          "driver_slug": "george-russell"
        },
        {
          "gap": "39.956",
          "pos": "4",
          "laps": "57",
          "name": "Max Verstappen",
          "pits": "1",
          "team": "Red Bull",
          "time": "+39.956s",
          "point": 12,
          "country": "Netherlands",
          "team_slug": "red-bull",
          "driver_slug": "max-verstappen"
        },
        {
          "gap": "48.067",
          "pos": "5",
          "laps": "57",
          "name": "Alexander Albon",
          "pits": "1",
          "team": "Williams",
          "time": "+48.067s",
          "point": 10,
          "country": "Thailand",
          "team_slug": "williams",
          "driver_slug": "alex-albon"
        },
        {
          "gap": "55.502",
          "pos": "6",
          "laps": "57",
          "name": "Kimi Antonelli",
          "pits": "1",
          "team": "Mercedes",
          "time": "+55.502s",
          "point": 8,
          "country": "Italy",
          "team_slug": "mercedes",
          "driver_slug": "kimi-antonelli"
        },
        {
          "gap": "57.036",
          "pos": "7",
          "laps": "57",
          "name": "Charles Leclerc",
          "pits": "1",
          "team": "Ferrari",
          "time": "+57.036s",
          "point": 6,
          "country": "Monaco",
          "team_slug": "ferrari",
          "driver_slug": "charles-leclerc"
        },
        {
          "gap": "60.186",
          "pos": "8",
          "laps": "57",
          "name": "Lewis Hamilton",
          "pits": "1",
          "team": "Ferrari",
          "time": "+60.186s",
          "point": 4,
          "country": "Great Britain",
          "team_slug": "ferrari",
          "driver_slug": "lewis-hamilton"
        },
        {
          "gap": "60.577",
          "pos": "9",
          "laps": "57",
          "name": "Carlos Sainz",
          "pits": "1",
          "team": "Williams",
          "time": "+60.577s",
          "point": 2,
          "country": "Spain",
          "team_slug": "williams",
          "driver_slug": "carlos-sainz"
        },
        {
          "gap": "74.434",
          "pos": "10",
          "laps": "57",
          "name": "Yuki Tsunoda",
          "pits": "1",
          "team": "Red Bull",
          "time": "+74.434s",
          "point": 1,
          "country": "Japan",
          "team_slug": "red-bull",
          "driver_slug": "yuki-tsunoda"
        },
        {
          "gap": "74.602",
          "pos": "11",
          "laps": "57",
          "name": "Isack Hadjar",
          "pits": "1",
          "team": "Racing Bulls",
          "time": "+74.602s",
          "point": 0,
          "country": "France",
          "team_slug": "racing-bulls",
          "driver_slug": "isack-hadjar"
        },
        {
          "gap": "82.006",
          "pos": "12",
          "laps": "57",
          "name": "Esteban Ocon",
          "pits": "1",
          "team": "Haas",
          "time": "+82.006s",
          "point": 0,
          "country": "France",
          "team_slug": "haas",
          "driver_slug": "esteban-ocon"
        },
        {
          "gap": "90.445",
          "pos": "13",
          "laps": "57",
          "name": "Pierre Gasly",
          "pits": "1",
          "team": "Alpine",
          "time": "+90.445s",
          "point": 0,
          "country": "France",
          "team_slug": "alpine",
          "driver_slug": "pierre-gasly"
        },
        {
          "gap": "1 LAP",
          "pos": "14",
          "laps": "56",
          "name": "Nico Hulkenberg",
          "pits": "1",
          "team": "Kick Sauber",
          "time": "1 LAP",
          "point": 0,
          "country": "Germany",
          "team_slug": "kick-sauber",
          "driver_slug": "nico-hulkenberg"
        },
        {
          "gap": "1 LAP",
          "pos": "15",
          "laps": "56",
          "name": "Fernando Alonso",
          "pits": "1",
          "team": "Aston Martin",
          "time": "1 LAP",
          "point": 0,
          "country": "Spain",
          "team_slug": "aston-martin",
          "driver_slug": "fernando-alonso"
        },
        {
          "gap": "1 LAP",
          "pos": "16",
          "laps": "56",
          "name": "Lance Stroll",
          "pits": "1",
          "team": "Aston Martin",
          "time": "1 LAP",
          "point": 0,
          "country": "Canada",
          "team_slug": "aston-martin",
          "driver_slug": "lance-stroll"
        },
        {
          "gap": "21 LAPS",
          "pos": "R",
          "laps": "36",
          "name": "Liam Lawson",
          "pits": "2",
          "team": "Racing Bulls",
          "time": "21 LAPS",
          "point": 0,
          "country": "New Zealand",
          "team_slug": "racing-bulls",
          "driver_slug": "liam-lawson"
        },
        {
          "gap": "27 LAPS",
          "pos": "R",
          "laps": "30",
          "name": "Gabriel Bortoleto",
          "pits": "1",
          "team": "Kick Sauber",
          "time": "27 LAPS",
          "point": 0,
          "country": "Brazil",
          "team_slug": "kick-sauber",
          "driver_slug": "gabriel-bortoleto"
        },
        {
          "gap": "30 LAPS",
          "pos": "R",
          "laps": "27",
          "name": "Oliver Bearman",
          "pits": "0",
          "team": "Haas",
          "time": "30 LAPS",
          "point": 0,
          "country": "Great Britain",
          "team_slug": "haas",
          "driver_slug": "oliver-bearman"
        },
        {
          "gap": "",
          "pos": "R",
          "laps": "0",
          "name": "Jack Doohan",
          "pits": "0",
          "team": "Alpine",
          "time": "",
          "point": 0,
          "country": "Australia",
          "team_slug": "alpine",
          "driver_slug": "jack-doohan"
        }
      ]
    },
    {
      "race_id": 1131,
      "race_name": "Saudi Arabian Grand Prix",
      "venue_name": "Jeddah",
      "match_date": "2025-04-20",
      "start_date": "2025-04-18T13:30:00Z",
      "end_date": "2025-04-20T19:00:00Z",
      "country": "Saudi Arabia",
      "country_code": "SAU",
      "sessions": [
        "Practice 1",
        "Practice 2",
        "Practice 3",
        "Qualifying 1",
        "Qualifying 2",
        "Qualifying 3",
        "Grid",
        "Race",
        "FastestLap"
      ],
      "results": [
        {
          "gap": "1:21:06.758",
          "pos": "1",
          "laps": "50",
          "name": "Oscar Piastri",
          "pits": "1",
          "team": "McLaren",
          "time": "1:21:06.758",
          "point": 25,
          "country": "Australia",
          "team_slug": "mclaren",
          "driver_slug": "oscar-piastri"
        },
        {
          "gap": "2.843",
          "pos": "2",
          "laps": "50",
          "name": "Max Verstappen",
          "pits": "1",
          "team": "Red Bull",
          "time": "+2.843s",
          "point": 18,
          "country": "Netherlands",
          "team_slug": "red-bull",
          "driver_slug": "max-verstappen"
        },
        {
          "gap": "8.104",
          "pos": "3",
          "laps": "50",
          "name": "Charles Leclerc",
          "pits": "1",
          "team": "Ferrari",
          "time": "+8.104s",
          "point": 15,
          "country": "Monaco",
          "team_slug": "ferrari",
          "driver_slug": "charles-leclerc"
        },
        {
          "gap": "9.196",
          "pos": "4",
          "laps": "50",
          "name": "Lando Norris",
          "pits": "1",
          "team": "McLaren",
          "time": "+9.196s",
          "point": 12,
          "country": "Great Britain",
          "team_slug": "mclaren",
          "driver_slug": "lando-norris"
        },
        {
          "gap": "27.236",
          "pos": "5",
          "laps": "50",
          "name": "George Russell",
          "pits": "1",
          "team": "Mercedes",
          "time": "+27.236s",
          "point": 10,
          "country": "Great Britain",
          "team_slug": "mercedes",
          "driver_slug": "george-russell"
        },
        {
          "gap": "34.688",
          "pos": "6",
          "laps": "50",
          "name": "Kimi Antonelli",
          "pits": "1",
          "team": "Mercedes",
          "time": "+34.688s",
          "point": 8,
          "country": "Italy",
          "team_slug": "mercedes",
          "driver_slug": "kimi-antonelli"
        },
        {
          "gap": "39.073",
          "pos": "7",
          "laps": "50",
          "name": "Lewis Hamilton",
          "pits": "1",
          "team": "Ferrari",
          "time": "+39.073s",
          "point": 6,
          "country": "Great Britain",
          "team_slug": "ferrari",
          "driver_slug": "lewis-hamilton"
        },
        {
          "gap": "64.630",
          "pos": "8",
          "laps": "50",
          "name": "Carlos Sainz",
          "pits": "1",
          "team": "Williams",
          "time": "+64.630s",
          "point": 4,
          "country": "Spain",
          "team_slug": "williams",
          "driver_slug": "carlos-sainz"
        },
        {
          "gap": "66.515",
          "pos": "9",
          "laps": "50",
          "name": "Alexander Albon",
          "pits": "1",
          "team": "Williams",
          "time": "+66.515s",
          "point": 2,
          "country": "Thailand",
          "team_slug": "williams",
          "driver_slug": "alex-albon"
        },
        {
          "gap": "67.091",
          "pos": "10",
          "laps": "50",
          "name": "Isack Hadjar",
          "pits": "1",
          "team": "Racing Bulls",
          "time": "+67.091s",
          "point": 1,
          "country": "France",
          "team_slug": "racing-bulls",
          "driver_slug": "isack-hadjar"
        },
        {
          "gap": "75.917",
          "pos": "11",
          "laps": "50",
          "name": "Fernando Alonso",
          "pits": "1",
          "team": "Aston Martin",
          "time": "+75.917s",
          "point": 0,
          "country": "Spain",
          "team_slug": "aston-martin",
          "driver_slug": "fernando-alonso"
        },
        {
          "gap": "78.451",
          "pos": "12",
          "laps": "50",
          "name": "Liam Lawson",
          "pits": "1",
          "team": "Racing Bulls",
          "time": "+78.451s",
          "point": 0,
          "country": "New Zealand",
          "team_slug": "racing-bulls",
          "driver_slug": "liam-lawson"
        },
        {
          "gap": "79.194",
          "pos": "13",
          "laps": "50",
          "name": "Oliver Bearman",
          "pits": "1",
          "team": "Haas",
          "time": "+79.194s",
          "point": 0,
          "country": "Great Britain",
          "team_slug": "haas",
          "driver_slug": "oliver-bearman"
        },
        {
          "gap": "99.723",
          "pos": "14",
          "laps": "50",
          "name": "Esteban Ocon",
          "pits": "1",
          "team": "Haas",
          "time": "+99.723s",
          "point": 0,
          "country": "France",
          "team_slug": "haas",
          "driver_slug": "esteban-ocon"
        },
        {
          "gap": "1 LAP",
          "pos": "15",
          "laps": "49",
          "name": "Nico Hulkenberg",
          "pits": "1",
          "team": "Kick Sauber",
          "time": "1 LAP",
          "point": 0,
          "country": "Germany",
          "team_slug": "kick-sauber",
          "driver_slug": "nico-hulkenberg"
        },
        {
          "gap": "1 LAP",
          "pos": "16",
          "laps": "49",
          "name": "Lance Stroll",
          "pits": "1",
          "team": "Aston Martin",
          "time": "1 LAP",
          "point": 0,
          "country": "Canada",
          "team_slug": "aston-martin",
          "driver_slug": "lance-stroll"
        },
        {
          "gap": "1 LAP",
          "pos": "17",
          "laps": "49",
          "name": "Jack Doohan",
          "pits": "2",
          "team": "Alpine",
          "time": "1 LAP",
          "point": 0,
          "country": "Australia",
          "team_slug": "alpine",
          "driver_slug": "jack-doohan"
        },
        {
          "gap": "1 LAP",
          "pos": "18",
          "laps": "49",
          "name": "Gabriel Bortoleto",
          "pits": "1",
          "team": "Kick Sauber",
          "time": "1 LAP",
          "point": 0,
          "country": "Brazil",
          "team_slug": "kick-sauber",
          "driver_slug": "gabriel-bortoleto"
        },
        {
          "gap": "49 LAPS",
          "pos": "R",
          "laps": "1",
          "name": "Yuki Tsunoda",
          "pits": "1",
          "team": "Red Bull",
          "time": "49 LAPS",
          "point": 0,
          "country": "Japan",
          "team_slug": "red-bull",
          "driver_slug": "yuki-tsunoda"
        },
        {
          "gap": "50 LAPS",
          "pos": "R",
          "laps": "0",
          "name": "Pierre Gasly",
          "pits": "0",
          "team": "Alpine",
          "time": "50 LAPS",
          "point": 0,
          "country": "France",
          "team_slug": "alpine",
          "driver_slug": "pierre-gasly"
        }
      ]
    },
    {
      "race_id": 1130,
      "race_name": "Bahrain Grand Prix",
      "venue_name": "Bahrain International",
      "match_date": "2025-04-13",
      "start_date": "2025-04-11T11:30:00Z",
      "end_date": "2025-04-13T17:00:00Z",
      "country": "Bahrain",
      "country_code": "BHR",
      "sessions": [
        "Practice 1",
        "Practice 2",
        "Practice 3",
        "Qualifying 1",
        "Qualifying 2",
        "Qualifying 3",
        "Grid",
        "Race",
        "FastestLap"
      ],
      "results": [
        {
          "gap": "1:35:39.435",
          "pos": "1",
          "laps": "57",
          "name": "Oscar Piastri",
          "pits": "2",
          "team": "McLaren",
          "time": "1:35:39.435",
          "point": 25,
          "country": "Australia",
          "team_slug": "mclaren",
          "driver_slug": "oscar-piastri"
        },
        {
          "gap": "15.499",
          "pos": "2",
          "laps": "57",
          "name": "George Russell",
          "pits": "2",
          "team": "Mercedes",
          "time": "+15.499s",
          "point": 18,
          "country": "Great Britain",
          "team_slug": "mercedes",
          "driver_slug": "george-russell"
        },
        {
          "gap": "16.273",
          "pos": "3",
          "laps": "57",
          "name": "Lando Norris",
          "pits": "2",
          "team": "McLaren",
          "time": "+16.273s",
          "point": 15,
          "country": "Great Britain",
          "team_slug": "mclaren",
          "driver_slug": "lando-norris"
        },
        {
          "gap": "19.679",
          "pos": "4",
          "laps": "57",
          "name": "Charles Leclerc",
          "pits": "2",
          "team": "Ferrari",
          "time": "+19.679s",
          "point": 12,
          "country": "Monaco",
          "team_slug": "ferrari",
          "driver_slug": "charles-leclerc"
        },
        {
          "gap": "27.993",
          "pos": "5",
          "laps": "57",
          "name": "Lewis Hamilton",
          "pits": "2",
          "team": "Ferrari",
          "time": "+27.993s",
          "point": 10,
          "country": "Great Britain",
          "team_slug": "ferrari",
          "driver_slug": "lewis-hamilton"
        },
        {
          "gap": "34.395",
          "pos": "6",
          "laps": "57",
          "name": "Max Verstappen",
          "pits": "2",
          "team": "Red Bull",
          "time": "+34.395s",
          "point": 8,
          "country": "Netherlands",
          "team_slug": "red-bull",
          "driver_slug": "max-verstappen"
        },
        {
          "gap": "36.002",
          "pos": "7",
          "laps": "57",
          "name": "Pierre Gasly",
          "pits": "2",
          "team": "Alpine",
          "time": "+36.002s",
          "point": 6,
          "country": "France",
          "team_slug": "alpine",
          "driver_slug": "pierre-gasly"
        },
        {
          "gap": "44.244",
          "pos": "8",
          "laps": "57",
          "name": "Esteban Ocon",
          "pits": "2",
          "team": "Haas",
          "time": "+44.244s",
          "point": 4,
          "country": "France",
          "team_slug": "haas",
          "driver_slug": "esteban-ocon"
        },
        {
          "gap": "45.061",
          "pos": "9",
          "laps": "57",
          "name": "Yuki Tsunoda",
          "pits": "2",
          "team": "Red Bull",
          "time": "+45.061s",
          "point": 2,
          "country": "Japan",
          "team_slug": "red-bull",
          "driver_slug": "yuki-tsunoda"
        },
        {
          "gap": "47.594",
          "pos": "10",
          "laps": "57",
          "name": "Oliver Bearman",
          "pits": "2",
          "team": "Haas",
          "time": "+47.594s",
          "point": 1,
          "country": "Great Britain",
          "team_slug": "haas",
          "driver_slug": "oliver-bearman"
        },
        {
          "gap": "48.016",
          "pos": "11",
          "laps": "57",
          "name": "Kimi Antonelli",
          "pits": "3",
          "team": "Mercedes",
          "time": "+48.016s",
          "point": 0,
          "country": "Italy",
          "team_slug": "mercedes",
          "driver_slug": "kimi-antonelli"
        },
        {
          "gap": "48.839",
          "pos": "12",
          "laps": "57",
          "name": "Alexander Albon",
          "pits": "2",
          "team": "Williams",
          "time": "+48.839s",
          "point": 0,
          "country": "Thailand",
          "team_slug": "williams",
          "driver_slug": "alex-albon"
        },
        {
          "gap": "56.314",
          "pos": "13",
          "laps": "57",
          "name": "Isack Hadjar",
          "pits": "2",
          "team": "Racing Bulls",
          "time": "+56.314s",
          "point": 0,
          "country": "France",
          "team_slug": "racing-bulls",
          "driver_slug": "isack-hadjar"
        },
        {
          "gap": "57.806",
          "pos": "14",
          "laps": "57",
          "name": "Jack Doohan",
          "pits": "2",
          "team": "Alpine",
          "time": "+57.806s",
          "point": 0,
          "country": "Australia",
          "team_slug": "alpine",
          "driver_slug": "jack-doohan"
        },
        {
          "gap": "60.340",
          "pos": "15",
          "laps": "57",
          "name": "Fernando Alonso",
          "pits": "2",
          "team": "Aston Martin",
          "time": "+60.340s",
          "point": 0,
          "country": "Spain",
          "team_slug": "aston-martin",
          "driver_slug": "fernando-alonso"
        },
        {
          "gap": "64.435",
          "pos": "16",
          "laps": "57",
          "name": "Liam Lawson",
          "pits": "2",
          "team": "Racing Bulls",
          "time": "+64.435s",
          "point": 0,
          "country": "New Zealand",
          "team_slug": "racing-bulls",
          "driver_slug": "liam-lawson"
        },
        {
          "gap": "65.489",
          "pos": "17",
          "laps": "57",
          "name": "Lance Stroll",
          "pits": "2",
          "team": "Aston Martin",
          "time": "+65.489s",
          "point": 0,
          "country": "Canada",
          "team_slug": "aston-martin",
          "driver_slug": "lance-stroll"
        },
        {
          "gap": "66.872",
          "pos": "18",
          "laps": "57",
          "name": "Gabriel Bortoleto",
          "pits": "2",
          "team": "Kick Sauber",
          "time": "+66.872s",
          "point": 0,
          "country": "Brazil",
          "team_slug": "kick-sauber",
          "driver_slug": "gabriel-bortoleto"
        },
        {
          "gap": "12 LAPS",
          "pos": "R",
          "laps": "45",
          "name": "Carlos Sainz",
          "pits": "4",
          "team": "Williams",
          "time": "12 LAPS",
          "point": 0,
          "country": "Spain",
          "team_slug": "williams",
          "driver_slug": "carlos-sainz"
        },
        {
          "gap": "53.472",
          "pos": "DSQ",
          "laps": "57",
          "name": "Nico Hulkenberg",
          "pits": "2",
          "team": "Kick Sauber",
          "time": "+53.472s",
          "point": 0,
          "country": "Germany",
          "team_slug": "kick-sauber",
          "driver_slug": "nico-hulkenberg"
        }
      ]
    },
    {
      "race_id": 1129,
      "race_name": "Japanese Grand Prix",
      "venue_name": "Suzuka",
      "match_date": "2025-04-06",
      "start_date": "2025-04-04T02:30:00Z",
      "end_date": "2025-04-06T07:00:00Z",
      "country": "Japan",
      "country_code": "JPN",
      "sessions": [
        "Practice 1",
        "Practice 2",
        "Practice 3",
        "Qualifying 1",
        "Qualifying 2",
        "Qualifying 3",
        "Grid",
        "Race",
        "FastestLap"
      ],
      "results": [
        {
          "gap": "1:22:06.983",
          "pos": "1",
          "laps": "53",
          "name": "Max Verstappen",
          "pits": "1",
          "team": "Red Bull",
          "time": "1:22:06.983",
          "point": 25,
          "country": "Netherlands",
          "team_slug": "red-bull",
          "driver_slug": "max-verstappen"
        },
        {
          "gap": "1.423",
          "pos": "2",
          "laps": "53",
          "name": "Lando Norris",
          "pits": "1",
          "team": "McLaren",
          "time": "+1.423s",
          "point": 18,
          "country": "Great Britain",
          "team_slug": "mclaren",
          "driver_slug": "lando-norris"
        },
        {
          "gap": "2.129",
          "pos": "3",
          "laps": "53",
          "name": "Oscar Piastri",
          "pits": "1",
          "team": "McLaren",
          "time": "+2.129s",
          "point": 15,
          "country": "Australia",
          "team_slug": "mclaren",
          "driver_slug": "oscar-piastri"
        },
        {
          "gap": "16.097",
          "pos": "4",
          "laps": "53",
          "name": "Charles Leclerc",
          "pits": "1",
          "team": "Ferrari",
          "time": "+16.097s",
          "point": 12,
          "country": "Monaco",
          "team_slug": "ferrari",
          "driver_slug": "charles-leclerc"
        },
        {
          "gap": "17.362",
          "pos": "5",
          "laps": "53",
          "name": "George Russell",
          "pits": "1",
          "team": "Mercedes",
          "time": "+17.362s",
          "point": 10,
          "country": "Great Britain",
          "team_slug": "mercedes",
          "driver_slug": "george-russell"
        },
        {
          "gap": "18.671",
          "pos": "6",
          "laps": "53",
          "name": "Kimi Antonelli",
          "pits": "1",
          "team": "Mercedes",
          "time": "+18.671s",
          "point": 8,
          "country": "Italy",
          "team_slug": "mercedes",
          "driver_slug": "kimi-antonelli"
        },
        {
          "gap": "29.182",
          "pos": "7",
          "laps": "53",
          "name": "Lewis Hamilton",
          "pits": "1",
          "team": "Ferrari",
          "time": "+29.182s",
          "point": 6,
          "country": "Great Britain",
          "team_slug": "ferrari",
          "driver_slug": "lewis-hamilton"
        },
        {
          "gap": "37.134",
          "pos": "8",
          "laps": "53",
          "name": "Isack Hadjar",
          "pits": "1",
          "team": "Racing Bulls",
          "time": "+37.134s",
          "point": 4,
          "country": "France",
          "team_slug": "racing-bulls",
          "driver_slug": "isack-hadjar"
        },
        {
          "gap": "40.367",
          "pos": "9",
          "laps": "53",
          "name": "Alexander Albon",
          "pits": "1",
          "team": "Williams",
          "time": "+40.367s",
          "point": 2,
          "country": "Thailand",
          "team_slug": "williams",
          "driver_slug": "alex-albon"
        },
        {
          "gap": "54.529",
          "pos": "10",
          "laps": "53",
          "name": "Oliver Bearman",
          "pits": "1",
          "team": "Haas",
          "time": "+54.529s",
          "point": 1,
          "country": "Great Britain",
          "team_slug": "haas",
          "driver_slug": "oliver-bearman"
        },
        {
          "gap": "57.333",
          "pos": "11",
          "laps": "53",
          "name": "Fernando Alonso",
          "pits": "1",
          "team": "Aston Martin",
          "time": "+57.333s",
          "point": 0,
          "country": "Spain",
          "team_slug": "aston-martin",
          "driver_slug": "fernando-alonso"
        },
        {
          "gap": "58.401",
          "pos": "12",
          "laps": "53",
          "name": "Yuki Tsunoda",
          "pits": "1",
          "team": "Red Bull",
          "time": "+58.401s",
          "point": 0,
          "country": "Japan",
          "team_slug": "red-bull",
          "driver_slug": "yuki-tsunoda"
        },
        {
          "gap": "62.122",
          "pos": "13",
          "laps": "53",
          "name": "Pierre Gasly",
          "pits": "1",
          "team": "Alpine",
          "time": "+62.122s",
          "point": 0,
          "country": "France",
          "team_slug": "alpine",
          "driver_slug": "pierre-gasly"
        },
        {
          "gap": "74.129",
          "pos": "14",
          "laps": "53",
          "name": "Carlos Sainz",
          "pits": "1",
          "team": "Williams",
          "time": "+74.129s",
          "point": 0,
          "country": "Spain",
          "team_slug": "williams",
          "driver_slug": "carlos-sainz"
        },
        {
          "gap": "81.314",
          "pos": "15",
          "laps": "53",
          "name": "Jack Doohan",
          "pits": "1",
          "team": "Alpine",
          "time": "+81.314s",
          "point": 0,
          "country": "Australia",
          "team_slug": "alpine",
          "driver_slug": "jack-doohan"
        },
        {
          "gap": "81.957",
          "pos": "16",
          "laps": "53",
          "name": "Nico Hulkenberg",
          "pits": "1",
          "team": "Kick Sauber",
          "time": "+81.957s",
          "point": 0,
          "country": "Germany",
          "team_slug": "kick-sauber",
          "driver_slug": "nico-hulkenberg"
        },
        {
          "gap": "82.734",
          "pos": "17",
          "laps": "53",
          "name": "Liam Lawson",
          "pits": "1",
          "team": "Racing Bulls",
          "time": "+82.734s",
          "point": 0,
          "country": "New Zealand",
          "team_slug": "racing-bulls",
          "driver_slug": "liam-lawson"
        },
        {
          "gap": "83.438",
          "pos": "18",
          "laps": "53",
          "name": "Esteban Ocon",
          "pits": "1",
          "team": "Haas",
          "time": "+83.438s",
          "point": 0,
          "country": "France",
          "team_slug": "haas",
          "driver_slug": "esteban-ocon"
        },
        {
          "gap": "83.897",
          "pos": "19",
          "laps": "53",
          "name": "Gabriel Bortoleto",
          "pits": "1",
          "team": "Kick Sauber",
          "time": "+83.897s",
          "point": 0,
          "country": "Brazil",
          "team_slug": "kick-sauber",
          "driver_slug": "gabriel-bortoleto"
        },
        {
          "gap": "1 LAP",
          "pos": "20",
          "laps": "52",
          "name": "Lance Stroll",
          "pits": "2",
          "team": "Aston Martin",
          "time": "1 LAP",
          "point": 0,
          "country": "Canada",
          "team_slug": "aston-martin",
          "driver_slug": "lance-stroll"
        }
      ]
    },
    {
      "race_id": 1128,
      "race_name": "Chinese Grand Prix",
      "venue_name": "Shanghai International",
      "match_date": "2025-03-23",
      "start_date": "2025-03-21T03:30:00Z",
      "end_date": "2025-03-23T09:00:00Z",
      "country": "China",
      "country_code": "CHN",
      "sessions": [
        "Practice 1",
        "Sprint Shootout 1",
        "Sprint Shootout 2",
        "Sprint Shootout 3",
        "Sprint Grid",
        "Sprint",
        "Qualifying 1",
        "Qualifying 2",
        "Qualifying 3",
        "Grid",
        "Race",
        "FastestLap"
      ],
      "results": [
        {
          "gap": "1:30:55.026",
          "pos": "1",
          "laps": "56",
          "name": "Oscar Piastri",
          "pits": "1",
          "team": "McLaren",
          "time": "1:30:55.026",
          "point": 25,
          "country": "Australia",
          "team_slug": "mclaren",
          "driver_slug": "oscar-piastri"
        },
        {
          "gap": "9.748",
          "pos": "2",
          "laps": "56",
          "name": "Lando Norris",
          "pits": "1",
          "team": "McLaren",
          "time": "+9.748s",
          "point": 18,
          "country": "Great Britain",
          "team_slug": "mclaren",
          "driver_slug": "lando-norris"
        },
        {
          "gap": "11.097",
          "pos": "3",
          "laps": "56",
          "name": "George Russell",
          "pits": "1",
          "team": "Mercedes",
          "time": "+11.097s",
          "point": 15,
          "country": "Great Britain",
          "team_slug": "mercedes",
          "driver_slug": "george-russell"
        },
        {
          "gap": "16.656",
          "pos": "4",
          "laps": "56",
          "name": "Max Verstappen",
          "pits": "1",
          "team": "Red Bull",
          "time": "+16.656s",
          "point": 12,
          "country": "Netherlands",
          "team_slug": "red-bull",
          "driver_slug": "max-verstappen"
        },
        {
          "gap": "49.969",
          "pos": "5",
          "laps": "56",
          "name": "Esteban Ocon",
          "pits": "1",
          "team": "Haas",
          "time": "+49.969s",
          "point": 10,
          "country": "France",
          "team_slug": "haas",
          "driver_slug": "esteban-ocon"
        },
        {
          "gap": "53.748",
          "pos": "6",
          "laps": "56",
          "name": "Kimi Antonelli",
          "pits": "1",
          "team": "Mercedes",
          "time": "+53.748s",
          "point": 8,
          "country": "Italy",
          "team_slug": "mercedes",
          "driver_slug": "kimi-antonelli"
        },
        {
          "gap": "56.321",
          "pos": "7",
          "laps": "56",
          "name": "Alexander Albon",
          "pits": "1",
          "team": "Williams",
          "time": "+56.321s",
          "point": 6,
          "country": "Thailand",
          "team_slug": "williams",
          "driver_slug": "alex-albon"
        },
        {
          "gap": "61.303",
          "pos": "8",
          "laps": "56",
          "name": "Oliver Bearman",
          "pits": "1",
          "team": "Haas",
          "time": "+61.303s",
          "point": 4,
          "country": "Great Britain",
          "team_slug": "haas",
          "driver_slug": "oliver-bearman"
        },
        {
          "gap": "70.204",
          "pos": "9",
          "laps": "56",
          "name": "Lance Stroll",
          "pits": "1",
          "team": "Aston Martin",
          "time": "+70.204s",
          "point": 2,
          "country": "Canada",
          "team_slug": "aston-martin",
          "driver_slug": "lance-stroll"
        },
        {
          "gap": "76.387",
          "pos": "10",
          "laps": "56",
          "name": "Carlos Sainz",
          "pits": "1",
          "team": "Williams",
          "time": "+76.387s",
          "point": 1,
          "country": "Spain",
          "team_slug": "williams",
          "driver_slug": "carlos-sainz"
        },
        {
          "gap": "78.875",
          "pos": "11",
          "laps": "56",
          "name": "Isack Hadjar",
          "pits": "2",
          "team": "Racing Bulls",
          "time": "+78.875s",
          "point": 0,
          "country": "France",
          "team_slug": "racing-bulls",
          "driver_slug": "isack-hadjar"
        },
        {
          "gap": "81.147",
          "pos": "16",
          "laps": "56",
          "name": "Liam Lawson",
          "pits": "2",
          "team": "Red Bull",
          "time": "+81.147s",
          "point": 0,
          "country": "New Zealand",
          "team_slug": "red-bull",
          "driver_slug": "liam-lawson"
        },
        {
          "gap": "88.401",
          "pos": "13",
          "laps": "56",
          "name": "Jack Doohan",
          "pits": "1",
          "team": "Alpine",
          "time": "+88.401s",
          "point": 0,
          "country": "Australia",
          "team_slug": "alpine",
          "driver_slug": "jack-doohan"
        },
        {
          "gap": "1 LAP",
          "pos": "14",
          "laps": "55",
          "name": "Gabriel Bortoleto",
          "pits": "2",
          "team": "Kick Sauber",
          "time": "1 LAP",
          "point": 0,
          "country": "Brazil",
          "team_slug": "kick-sauber",
          "driver_slug": "gabriel-bortoleto"
        },
        {
          "gap": "1 LAP",
          "pos": "15",
          "laps": "55",
          "name": "Nico Hulkenberg",
          "pits": "1",
          "team": "Kick Sauber",
          "time": "1 LAP",
          "point": 0,
          "country": "Germany",
          "team_slug": "kick-sauber",
          "driver_slug": "nico-hulkenberg"
        },
        {
          "gap": "1 LAP",
          "pos": "12",
          "laps": "55",
          "name": "Yuki Tsunoda",
          "pits": "3",
          "team": "Racing Bulls",
          "time": "1 LAP",
          "point": 0,
          "country": "Japan",
          "team_slug": "racing-bulls",
          "driver_slug": "yuki-tsunoda"
        },
        {
          "gap": "52 LAPS",
          "pos": "R",
          "laps": "4",
          "name": "Fernando Alonso",
          "pits": "1",
          "team": "Aston Martin",
          "time": "52 LAPS",
          "point": 0,
          "country": "Spain",
          "team_slug": "aston-martin",
          "driver_slug": "fernando-alonso"
        },
        {
          "gap": "23.211",
          "pos": "DSQ",
          "laps": "56",
          "name": "Charles Leclerc",
          "pits": "1",
          "team": "Ferrari",
          "time": "+23.211s",
          "point": 0,
          "country": "Monaco",
          "team_slug": "ferrari",
          "driver_slug": "charles-leclerc"
        },
        {
          "gap": "25.381",
          "pos": "DSQ",
          "laps": "56",
          "name": "Lewis Hamilton",
          "pits": "2",
          "team": "Ferrari",
          "time": "+25.381s",
          "point": 0,
          "country": "Great Britain",
          "team_slug": "ferrari",
          "driver_slug": "lewis-hamilton"
        },
        {
          "gap": "67.195",
          "pos": "DSQ",
          "laps": "56",
          "name": "Pierre Gasly",
          "pits": "1",
          "team": "Alpine",
          "time": "+67.195s",
          "point": 0,
          "country": "France",
          "team_slug": "alpine",
          "driver_slug": "pierre-gasly"
        }
      ]
    },
    {
      "race_id": 1127,
      "race_name": "Australian Grand Prix",
      "venue_name": "Albert Park Circuit",
      "match_date": "2025-03-16",
      "start_date": "2025-03-14T01:30:00Z",
      "end_date": "2025-03-16T06:00:00Z",
      "country": "Australia",
      "country_code": "AUS",
      "sessions": [
        "Practice 1",
        "Practice 2",
        "Practice 3",
        "Qualifying 1",
        "Qualifying 2",
        "Qualifying 3",
        "Grid",
        "Race",
        "FastestLap"
      ],
      "results": [
        {
          "gap": "1:42:06.304",
          "pos": "1",
          "laps": "57",
          "name": "Lando Norris",
          "pits": "5",
          "team": "McLaren",
          "time": "1:42:06.304",
          "point": 25,
          "country": "Great Britain",
          "team_slug": "mclaren",
          "driver_slug": "lando-norris"
        },
        {
          "gap": "0.895",
          "pos": "2",
          "laps": "57",
          "name": "Max Verstappen",
          "pits": "5",
          "team": "Red Bull",
          "time": "+0.895s",
          "point": 18,
          "country": "Netherlands",
          "team_slug": "red-bull",
          "driver_slug": "max-verstappen"
        },
        {
          "gap": "8.481",
          "pos": "3",
          "laps": "57",
          "name": "George Russell",
          "pits": "5",
          "team": "Mercedes",
          "time": "+8.481s",
          "point": 15,
          "country": "Great Britain",
          "team_slug": "mercedes",
          "driver_slug": "george-russell"
        },
        {
          "gap": "10.135",
          "pos": "4",
          "laps": "57",
          "name": "Kimi Antonelli",
          "pits": "5",
          "team": "Mercedes",
          "time": "+10.135s",
          "point": 12,
          "country": "Italy",
          "team_slug": "mercedes",
          "driver_slug": "kimi-antonelli"
        },
        {
          "gap": "12.773",
          "pos": "5",
          "laps": "57",
          "name": "Alexander Albon",
          "pits": "5",
          "team": "Williams",
          "time": "+12.773s",
          "point": 10,
          "country": "Thailand",
          "team_slug": "williams",
          "driver_slug": "alex-albon"
        },
        {
          "gap": "17.413",
          "pos": "6",
          "laps": "57",
          "name": "Lance Stroll",
          "pits": "5",
          "team": "Aston Martin",
          "time": "+17.413s",
          "point": 8,
          "country": "Canada",
          "team_slug": "aston-martin",
          "driver_slug": "lance-stroll"
        },
        {
          "gap": "18.423",
          "pos": "7",
          "laps": "57",
          "name": "Nico Hulkenberg",
          "pits": "5",
          "team": "Kick Sauber",
          "time": "+18.423s",
          "point": 6,
          "country": "Germany",
          "team_slug": "kick-sauber",
          "driver_slug": "nico-hulkenberg"
        },
        {
          "gap": "19.826",
          "pos": "8",
          "laps": "57",
          "name": "Charles Leclerc",
          "pits": "5",
          "team": "Ferrari",
          "time": "+19.826s",
          "point": 4,
          "country": "Monaco",
          "team_slug": "ferrari",
          "driver_slug": "charles-leclerc"
        },
        {
          "gap": "20.448",
          "pos": "9",
          "laps": "57",
          "name": "Oscar Piastri",
          "pits": "5",
          "team": "McLaren",
          "time": "+20.448s",
          "point": 2,
          "country": "Australia",
          "team_slug": "mclaren",
          "driver_slug": "oscar-piastri"
        },
        {
          "gap": "22.473",
          "pos": "10",
          "laps": "57",
          "name": "Lewis Hamilton",
          "pits": "5",
          "team": "Ferrari",
          "time": "+22.473s",
          "point": 1,
          "country": "Great Britain",
          "team_slug": "ferrari",
          "driver_slug": "lewis-hamilton"
        },
        {
          "gap": "26.502",
          "pos": "11",
          "laps": "57",
          "name": "Pierre Gasly",
          "pits": "5",
          "team": "Alpine",
          "time": "+26.502s",
          "point": 0,
          "country": "France",
          "team_slug": "alpine",
          "driver_slug": "pierre-gasly"
        },
        {
          "gap": "29.884",
          "pos": "15",
          "laps": "57",
          "name": "Yuki Tsunoda",
          "pits": "5",
          "team": "Racing Bulls",
          "time": "+29.884s",
          "point": 0,
          "country": "Japan",
          "team_slug": "racing-bulls",
          "driver_slug": "yuki-tsunoda"
        },
        {
          "gap": "33.161",
          "pos": "13",
          "laps": "57",
          "name": "Esteban Ocon",
          "pits": "5",
          "team": "Haas",
          "time": "+33.161s",
          "point": 0,
          "country": "France",
          "team_slug": "haas",
          "driver_slug": "esteban-ocon"
        },
        {
          "gap": "40.351",
          "pos": "14",
          "laps": "57",
          "name": "Oliver Bearman",
          "pits": "5",
          "team": "Haas",
          "time": "+40.351s",
          "point": 0,
          "country": "Great Britain",
          "team_slug": "haas",
          "driver_slug": "oliver-bearman"
        },
        {
          "gap": "11 LAPS",
          "pos": "12",
          "laps": "46",
          "name": "Liam Lawson",
          "pits": "4",
          "team": "Red Bull",
          "time": "11 LAPS",
          "point": 0,
          "country": "New Zealand",
          "team_slug": "red-bull",
          "driver_slug": "liam-lawson"
        },
        {
          "gap": "12 LAPS",
          "pos": "16",
          "laps": "45",
          "name": "Gabriel Bortoleto",
          "pits": "5",
          "team": "Kick Sauber",
          "time": "12 LAPS",
          "point": 0,
          "country": "Brazil",
          "team_slug": "kick-sauber",
          "driver_slug": "gabriel-bortoleto"
        },
        {
          "gap": "25 LAPS",
          "pos": "17",
          "laps": "32",
          "name": "Fernando Alonso",
          "pits": "3",
          "team": "Aston Martin",
          "time": "25 LAPS",
          "point": 0,
          "country": "Spain",
          "team_slug": "aston-martin",
          "driver_slug": "fernando-alonso"
        },
        {
          "gap": "",
          "pos": "DNS",
          "laps": "0",
          "name": "Carlos Sainz",
          "pits": "0",
          "team": "Williams",
          "time": "",
          "point": 0,
          "country": "Spain",
          "team_slug": "williams",
          "driver_slug": "carlos-sainz"
        },
        {
          "gap": "",
          "pos": "DNS",
          "laps": "0",
          "name": "Jack Doohan",
          "pits": "0",
          "team": "Alpine",
          "time": "",
          "point": 0,
          "country": "Australia",
          "team_slug": "alpine",
          "driver_slug": "jack-doohan"
        },
        {
          "gap": "",
          "pos": "DNS",
          "laps": "0",
          "name": "Isack Hadjar",
          "pits": "0",
          "team": "Racing Bulls",
          "time": "",
          "point": 0,
          "country": "France",
          "team_slug": "racing-bulls",
          "driver_slug": "isack-hadjar"
        }
      ]
    }
  ]
}

export { allResults };